# Generated by Django 5.1 on 2024-09-16 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('difficulty', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=1, help_text='Difficulty of the task, from 1 to 5 starts.')),
                ('description', models.TextField(max_length=100)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kid')),
                ('tags', models.ManyToManyField(related_name='tasks', to='tasks.tag')),
            ],
        ),
    ]
